name: pull_req workflow

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.7"